services:
  depths:
    container_name: depths
    env_file:
      - env/dev.env
    build:
      context: ./microservices/depths
      dockerfile: Dockerfile
    volumes:
      - ./microservices/depths:/usr/src/app
    command: air
    ports:
      - 8008:8000
    working_dir: /usr/src/app
    depends_on:
      - redis
      - mongo
    restart: unless-stopped
    networks:
      - crypto-network

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - crypto-network

  redis:
    container_name: redis
    image: redis:7.0
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - crypto-network

networks:
  crypto-network:
    driver: bridge

volumes:
  mongodb_data_container: null
